import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Sujit',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Budhiti Brassware',
      slug: 'Budhiti Brassware',
      category: 'Brassware',
      image: '/Images/bidhiti.jpg',
      price: 359,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality brassware',
    },
    {
      // _id: '2',
      name: 'Wood and Bamboo',
      slug: 'Wood and Bamboo',
      category: 'Shirts',
      image: '/Images/woodAndBamboo.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality wood n bambooo',
    },
    {
      // _id: '3',
      name: 'Terracotta Pottery',
      slug: 'Terracotta Pottery',
      category: 'Shirts',
      image: '/Images/TerracottaPottery.jpg',
      price: 300,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Pottery',
    },
    {
      // _id: '4',
      name: 'Kullu Woolen Caps',
      slug: 'Kullu Woolen Caps',
      category: 'Shirts',
      image: '/images/KulluWoolenCaps.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality Caps',
    },
  ],
};

export default data;
